### ISSUE TITLE
Error downloading VUI

### ISSUE THREAD

**Issue by SentaiBrad** [TheMrNewVegas/TTWTrueVegas#55]
I am able to download the file manually, but I did get this error when attempting to download the pack.

```
00:00:53.721 [ERROR] (Wabbajack.Installer.StandardInstaller) Download error for file Vanilla_UI_Plus_New_Vegas_944.2.7z|Wabbajack.Networking.Http.HttpException: Http Error BadRequest - Bad Request
   at Wabbajack.Networking.Http.SingleThreadedDownloader.Download(HttpRequestMessage message, AbsolutePath outputPath, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Networking.Http\SingleThreadedDownloader.cs:line 34
   at Wabbajack.Downloaders.Http.HttpDownloader.Download(Archive archive, Http state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Http\HttpDownloader.cs:line 96
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 136
   at Wabbajack.Installer.AInstaller`1.DownloadArchive(Archive archive, Boolean download, CancellationToken token, Nullable`1 destination) in c:\oss\wabbajack\Wabbajack.Installer\AInstaller.cs:line 369
```

**Comment by TheMrNewVegas** [comment]
This is a common occurrence with MODDB & Wabbajack in general
